// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: bot.proto

package botproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VagueService_ChatStreamMultipleEvent_FullMethodName = "/chat.VagueService/ChatStreamMultipleEvent"
	VagueService_GetLastEventRevision_FullMethodName    = "/chat.VagueService/GetLastEventRevision"
	VagueService_GetLastViewRevision_FullMethodName     = "/chat.VagueService/GetLastViewRevision"
	VagueService_RegisterPublicKey_FullMethodName       = "/chat.VagueService/RegisterPublicKey"
	VagueService_GetPublicKey_FullMethodName            = "/chat.VagueService/GetPublicKey"
	VagueService_SendMessage_FullMethodName             = "/chat.VagueService/SendMessage"
	VagueService_GetMessage_FullMethodName              = "/chat.VagueService/GetMessage"
	VagueService_DeleteMessage_FullMethodName           = "/chat.VagueService/DeleteMessage"
	VagueService_RefreshToken_FullMethodName            = "/chat.VagueService/RefreshToken"
	VagueService_EditMessage_FullMethodName             = "/chat.VagueService/EditMessage"
	VagueService_GetOriginMessage_FullMethodName        = "/chat.VagueService/GetOriginMessage"
	VagueService_UploadMedia_FullMethodName             = "/chat.VagueService/UploadMedia"
	VagueService_BackupE2EEKey_FullMethodName           = "/chat.VagueService/BackupE2EEKey"
	VagueService_RestoreE2EEKey_FullMethodName          = "/chat.VagueService/RestoreE2EEKey"
	VagueService_UpdateSettings_FullMethodName          = "/chat.VagueService/UpdateSettings"
	VagueService_GetSettings_FullMethodName             = "/chat.VagueService/GetSettings"
	VagueService_GetProfile_FullMethodName              = "/chat.VagueService/GetProfile"
	VagueService_UpdateProfile_FullMethodName           = "/chat.VagueService/UpdateProfile"
	VagueService_SearchUsers_FullMethodName             = "/chat.VagueService/SearchUsers"
	VagueService_AddFriend_FullMethodName               = "/chat.VagueService/AddFriend"
	VagueService_GetFriends_FullMethodName              = "/chat.VagueService/GetFriends"
	VagueService_GetContacts_FullMethodName             = "/chat.VagueService/GetContacts"
	VagueService_UpdateContact_FullMethodName           = "/chat.VagueService/UpdateContact"
	VagueService_GetBlockedUsers_FullMethodName         = "/chat.VagueService/GetBlockedUsers"
	VagueService_CreateGroup_FullMethodName             = "/chat.VagueService/CreateGroup"
	VagueService_GetGroup_FullMethodName                = "/chat.VagueService/GetGroup"
	VagueService_GetMyGroups_FullMethodName             = "/chat.VagueService/GetMyGroups"
	VagueService_UpdateGroup_FullMethodName             = "/chat.VagueService/UpdateGroup"
	VagueService_InviteMember_FullMethodName            = "/chat.VagueService/InviteMember"
	VagueService_RemoveMember_FullMethodName            = "/chat.VagueService/RemoveMember"
	VagueService_RespondInvitation_FullMethodName       = "/chat.VagueService/RespondInvitation"
	VagueService_CancelInvitation_FullMethodName        = "/chat.VagueService/CancelInvitation"
	VagueService_GetMyGroupInvitations_FullMethodName   = "/chat.VagueService/GetMyGroupInvitations"
	VagueService_GenerateGroupUrl_FullMethodName        = "/chat.VagueService/GenerateGroupUrl"
	VagueService_JoinGroupByUrl_FullMethodName          = "/chat.VagueService/JoinGroupByUrl"
	VagueService_FindGroupByInviteCode_FullMethodName   = "/chat.VagueService/FindGroupByInviteCode"
	VagueService_GetGroupWithDisplayName_FullMethodName = "/chat.VagueService/GetGroupWithDisplayName"
	VagueService_LeaveGroup_FullMethodName              = "/chat.VagueService/LeaveGroup"
)

// VagueServiceClient is the client API for VagueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VagueServiceClient interface {
	ChatStreamMultipleEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, MultipleStreamResponse], error)
	GetLastEventRevision(ctx context.Context, in *GetLastEventRevisionRequest, opts ...grpc.CallOption) (*GetLastEventRevisionResponse, error)
	GetLastViewRevision(ctx context.Context, in *GetLastViewRevisionRequest, opts ...grpc.CallOption) (*GetLastViewRevisionResponse, error)
	RegisterPublicKey(ctx context.Context, in *RegisterPublicKeyRequest, opts ...grpc.CallOption) (*RegisterPublicKeyResponse, error)
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EditMessageResponse, error)
	GetOriginMessage(ctx context.Context, in *GetOriginMessageRequest, opts ...grpc.CallOption) (*GetOriginMessageResponse, error)
	UploadMedia(ctx context.Context, in *UploadMediaRequest, opts ...grpc.CallOption) (*UploadMediaResponse, error)
	BackupE2EEKey(ctx context.Context, in *BackupE2EEKeyRequest, opts ...grpc.CallOption) (*BackupE2EEKeyResponse, error)
	RestoreE2EEKey(ctx context.Context, in *RestoreE2EEKeyRequest, opts ...grpc.CallOption) (*RestoreE2EEKeyResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error)
	UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	GetBlockedUsers(ctx context.Context, in *GetBlockedUsersRequest, opts ...grpc.CallOption) (*GetBlockedUsersResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	GetMyGroups(ctx context.Context, in *GetMyGroupsRequest, opts ...grpc.CallOption) (*GetMyGroupsResponse, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	RespondInvitation(ctx context.Context, in *RespondInvitationRequest, opts ...grpc.CallOption) (*RespondInvitationResponse, error)
	CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*CancelInvitationResponse, error)
	GetMyGroupInvitations(ctx context.Context, in *GetMyGroupInvitationsRequest, opts ...grpc.CallOption) (*GetMyGroupInvitationsResponse, error)
	GenerateGroupUrl(ctx context.Context, in *GenerateGroupUrlRequest, opts ...grpc.CallOption) (*GenerateGroupUrlResponse, error)
	JoinGroupByUrl(ctx context.Context, in *JoinGroupByUrlRequest, opts ...grpc.CallOption) (*JoinGroupByUrlResponse, error)
	FindGroupByInviteCode(ctx context.Context, in *FindGroupByInviteCodeRequest, opts ...grpc.CallOption) (*FindGroupByInviteCodeResponse, error)
	GetGroupWithDisplayName(ctx context.Context, in *GetGroupWithDisplayNameRequest, opts ...grpc.CallOption) (*GetGroupWithDisplayNameResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error)
}

type vagueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVagueServiceClient(cc grpc.ClientConnInterface) VagueServiceClient {
	return &vagueServiceClient{cc}
}

func (c *vagueServiceClient) ChatStreamMultipleEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, MultipleStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VagueService_ServiceDesc.Streams[0], VagueService_ChatStreamMultipleEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, MultipleStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VagueService_ChatStreamMultipleEventClient = grpc.BidiStreamingClient[StreamRequest, MultipleStreamResponse]

func (c *vagueServiceClient) GetLastEventRevision(ctx context.Context, in *GetLastEventRevisionRequest, opts ...grpc.CallOption) (*GetLastEventRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastEventRevisionResponse)
	err := c.cc.Invoke(ctx, VagueService_GetLastEventRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetLastViewRevision(ctx context.Context, in *GetLastViewRevisionRequest, opts ...grpc.CallOption) (*GetLastViewRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastViewRevisionResponse)
	err := c.cc.Invoke(ctx, VagueService_GetLastViewRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) RegisterPublicKey(ctx context.Context, in *RegisterPublicKeyRequest, opts ...grpc.CallOption) (*RegisterPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPublicKeyResponse)
	err := c.cc.Invoke(ctx, VagueService_RegisterPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, VagueService_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, VagueService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, VagueService_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, VagueService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, VagueService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EditMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditMessageResponse)
	err := c.cc.Invoke(ctx, VagueService_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetOriginMessage(ctx context.Context, in *GetOriginMessageRequest, opts ...grpc.CallOption) (*GetOriginMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOriginMessageResponse)
	err := c.cc.Invoke(ctx, VagueService_GetOriginMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) UploadMedia(ctx context.Context, in *UploadMediaRequest, opts ...grpc.CallOption) (*UploadMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadMediaResponse)
	err := c.cc.Invoke(ctx, VagueService_UploadMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) BackupE2EEKey(ctx context.Context, in *BackupE2EEKeyRequest, opts ...grpc.CallOption) (*BackupE2EEKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupE2EEKeyResponse)
	err := c.cc.Invoke(ctx, VagueService_BackupE2EEKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) RestoreE2EEKey(ctx context.Context, in *RestoreE2EEKeyRequest, opts ...grpc.CallOption) (*RestoreE2EEKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreE2EEKeyResponse)
	err := c.cc.Invoke(ctx, VagueService_RestoreE2EEKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSettingsResponse)
	err := c.cc.Invoke(ctx, VagueService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, VagueService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, VagueService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, VagueService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResponse)
	err := c.cc.Invoke(ctx, VagueService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFriendResponse)
	err := c.cc.Invoke(ctx, VagueService_AddFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, VagueService_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContactsResponse)
	err := c.cc.Invoke(ctx, VagueService_GetContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContactResponse)
	err := c.cc.Invoke(ctx, VagueService_UpdateContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetBlockedUsers(ctx context.Context, in *GetBlockedUsersRequest, opts ...grpc.CallOption) (*GetBlockedUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockedUsersResponse)
	err := c.cc.Invoke(ctx, VagueService_GetBlockedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, VagueService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, VagueService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetMyGroups(ctx context.Context, in *GetMyGroupsRequest, opts ...grpc.CallOption) (*GetMyGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyGroupsResponse)
	err := c.cc.Invoke(ctx, VagueService_GetMyGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, VagueService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResponse)
	err := c.cc.Invoke(ctx, VagueService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, VagueService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) RespondInvitation(ctx context.Context, in *RespondInvitationRequest, opts ...grpc.CallOption) (*RespondInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondInvitationResponse)
	err := c.cc.Invoke(ctx, VagueService_RespondInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*CancelInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInvitationResponse)
	err := c.cc.Invoke(ctx, VagueService_CancelInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetMyGroupInvitations(ctx context.Context, in *GetMyGroupInvitationsRequest, opts ...grpc.CallOption) (*GetMyGroupInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyGroupInvitationsResponse)
	err := c.cc.Invoke(ctx, VagueService_GetMyGroupInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GenerateGroupUrl(ctx context.Context, in *GenerateGroupUrlRequest, opts ...grpc.CallOption) (*GenerateGroupUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateGroupUrlResponse)
	err := c.cc.Invoke(ctx, VagueService_GenerateGroupUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) JoinGroupByUrl(ctx context.Context, in *JoinGroupByUrlRequest, opts ...grpc.CallOption) (*JoinGroupByUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupByUrlResponse)
	err := c.cc.Invoke(ctx, VagueService_JoinGroupByUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) FindGroupByInviteCode(ctx context.Context, in *FindGroupByInviteCodeRequest, opts ...grpc.CallOption) (*FindGroupByInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindGroupByInviteCodeResponse)
	err := c.cc.Invoke(ctx, VagueService_FindGroupByInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) GetGroupWithDisplayName(ctx context.Context, in *GetGroupWithDisplayNameRequest, opts ...grpc.CallOption) (*GetGroupWithDisplayNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupWithDisplayNameResponse)
	err := c.cc.Invoke(ctx, VagueService_GetGroupWithDisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vagueServiceClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupResponse)
	err := c.cc.Invoke(ctx, VagueService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VagueServiceServer is the server API for VagueService service.
// All implementations must embed UnimplementedVagueServiceServer
// for forward compatibility.
type VagueServiceServer interface {
	ChatStreamMultipleEvent(grpc.BidiStreamingServer[StreamRequest, MultipleStreamResponse]) error
	GetLastEventRevision(context.Context, *GetLastEventRevisionRequest) (*GetLastEventRevisionResponse, error)
	GetLastViewRevision(context.Context, *GetLastViewRevisionRequest) (*GetLastViewRevisionResponse, error)
	RegisterPublicKey(context.Context, *RegisterPublicKeyRequest) (*RegisterPublicKeyResponse, error)
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	EditMessage(context.Context, *EditMessageRequest) (*EditMessageResponse, error)
	GetOriginMessage(context.Context, *GetOriginMessageRequest) (*GetOriginMessageResponse, error)
	UploadMedia(context.Context, *UploadMediaRequest) (*UploadMediaResponse, error)
	BackupE2EEKey(context.Context, *BackupE2EEKeyRequest) (*BackupE2EEKeyResponse, error)
	RestoreE2EEKey(context.Context, *RestoreE2EEKeyRequest) (*RestoreE2EEKeyResponse, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error)
	GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	GetContacts(context.Context, *GetContactsRequest) (*GetContactsResponse, error)
	UpdateContact(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	GetBlockedUsers(context.Context, *GetBlockedUsersRequest) (*GetBlockedUsersResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	GetMyGroups(context.Context, *GetMyGroupsRequest) (*GetMyGroupsResponse, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	RespondInvitation(context.Context, *RespondInvitationRequest) (*RespondInvitationResponse, error)
	CancelInvitation(context.Context, *CancelInvitationRequest) (*CancelInvitationResponse, error)
	GetMyGroupInvitations(context.Context, *GetMyGroupInvitationsRequest) (*GetMyGroupInvitationsResponse, error)
	GenerateGroupUrl(context.Context, *GenerateGroupUrlRequest) (*GenerateGroupUrlResponse, error)
	JoinGroupByUrl(context.Context, *JoinGroupByUrlRequest) (*JoinGroupByUrlResponse, error)
	FindGroupByInviteCode(context.Context, *FindGroupByInviteCodeRequest) (*FindGroupByInviteCodeResponse, error)
	GetGroupWithDisplayName(context.Context, *GetGroupWithDisplayNameRequest) (*GetGroupWithDisplayNameResponse, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error)
	mustEmbedUnimplementedVagueServiceServer()
}

// UnimplementedVagueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVagueServiceServer struct{}

func (UnimplementedVagueServiceServer) ChatStreamMultipleEvent(grpc.BidiStreamingServer[StreamRequest, MultipleStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ChatStreamMultipleEvent not implemented")
}
func (UnimplementedVagueServiceServer) GetLastEventRevision(context.Context, *GetLastEventRevisionRequest) (*GetLastEventRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastEventRevision not implemented")
}
func (UnimplementedVagueServiceServer) GetLastViewRevision(context.Context, *GetLastViewRevisionRequest) (*GetLastViewRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastViewRevision not implemented")
}
func (UnimplementedVagueServiceServer) RegisterPublicKey(context.Context, *RegisterPublicKeyRequest) (*RegisterPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPublicKey not implemented")
}
func (UnimplementedVagueServiceServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedVagueServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedVagueServiceServer) GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedVagueServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedVagueServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedVagueServiceServer) EditMessage(context.Context, *EditMessageRequest) (*EditMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedVagueServiceServer) GetOriginMessage(context.Context, *GetOriginMessageRequest) (*GetOriginMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOriginMessage not implemented")
}
func (UnimplementedVagueServiceServer) UploadMedia(context.Context, *UploadMediaRequest) (*UploadMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedVagueServiceServer) BackupE2EEKey(context.Context, *BackupE2EEKeyRequest) (*BackupE2EEKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupE2EEKey not implemented")
}
func (UnimplementedVagueServiceServer) RestoreE2EEKey(context.Context, *RestoreE2EEKeyRequest) (*RestoreE2EEKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreE2EEKey not implemented")
}
func (UnimplementedVagueServiceServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedVagueServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*GetSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedVagueServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedVagueServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedVagueServiceServer) SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedVagueServiceServer) AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFriend not implemented")
}
func (UnimplementedVagueServiceServer) GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedVagueServiceServer) GetContacts(context.Context, *GetContactsRequest) (*GetContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedVagueServiceServer) UpdateContact(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContact not implemented")
}
func (UnimplementedVagueServiceServer) GetBlockedUsers(context.Context, *GetBlockedUsersRequest) (*GetBlockedUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockedUsers not implemented")
}
func (UnimplementedVagueServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedVagueServiceServer) GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedVagueServiceServer) GetMyGroups(context.Context, *GetMyGroupsRequest) (*GetMyGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyGroups not implemented")
}
func (UnimplementedVagueServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedVagueServiceServer) InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedVagueServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedVagueServiceServer) RespondInvitation(context.Context, *RespondInvitationRequest) (*RespondInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondInvitation not implemented")
}
func (UnimplementedVagueServiceServer) CancelInvitation(context.Context, *CancelInvitationRequest) (*CancelInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInvitation not implemented")
}
func (UnimplementedVagueServiceServer) GetMyGroupInvitations(context.Context, *GetMyGroupInvitationsRequest) (*GetMyGroupInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyGroupInvitations not implemented")
}
func (UnimplementedVagueServiceServer) GenerateGroupUrl(context.Context, *GenerateGroupUrlRequest) (*GenerateGroupUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateGroupUrl not implemented")
}
func (UnimplementedVagueServiceServer) JoinGroupByUrl(context.Context, *JoinGroupByUrlRequest) (*JoinGroupByUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroupByUrl not implemented")
}
func (UnimplementedVagueServiceServer) FindGroupByInviteCode(context.Context, *FindGroupByInviteCodeRequest) (*FindGroupByInviteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindGroupByInviteCode not implemented")
}
func (UnimplementedVagueServiceServer) GetGroupWithDisplayName(context.Context, *GetGroupWithDisplayNameRequest) (*GetGroupWithDisplayNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupWithDisplayName not implemented")
}
func (UnimplementedVagueServiceServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedVagueServiceServer) mustEmbedUnimplementedVagueServiceServer() {}
func (UnimplementedVagueServiceServer) testEmbeddedByValue()                      {}

// UnsafeVagueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VagueServiceServer will
// result in compilation errors.
type UnsafeVagueServiceServer interface {
	mustEmbedUnimplementedVagueServiceServer()
}

func RegisterVagueServiceServer(s grpc.ServiceRegistrar, srv VagueServiceServer) {
	// If the following call panics, it indicates UnimplementedVagueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VagueService_ServiceDesc, srv)
}

func _VagueService_ChatStreamMultipleEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VagueServiceServer).ChatStreamMultipleEvent(&grpc.GenericServerStream[StreamRequest, MultipleStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VagueService_ChatStreamMultipleEventServer = grpc.BidiStreamingServer[StreamRequest, MultipleStreamResponse]

func _VagueService_GetLastEventRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastEventRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetLastEventRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetLastEventRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetLastEventRevision(ctx, req.(*GetLastEventRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetLastViewRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastViewRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetLastViewRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetLastViewRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetLastViewRevision(ctx, req.(*GetLastViewRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_RegisterPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).RegisterPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_RegisterPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).RegisterPublicKey(ctx, req.(*RegisterPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).EditMessage(ctx, req.(*EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetOriginMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetOriginMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetOriginMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetOriginMessage(ctx, req.(*GetOriginMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_UploadMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).UploadMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_UploadMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).UploadMedia(ctx, req.(*UploadMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_BackupE2EEKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupE2EEKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).BackupE2EEKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_BackupE2EEKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).BackupE2EEKey(ctx, req.(*BackupE2EEKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_RestoreE2EEKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreE2EEKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).RestoreE2EEKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_RestoreE2EEKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).RestoreE2EEKey(ctx, req.(*RestoreE2EEKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).SearchUsers(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_AddFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetContacts(ctx, req.(*GetContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_UpdateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).UpdateContact(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetBlockedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockedUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetBlockedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetBlockedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetBlockedUsers(ctx, req.(*GetBlockedUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetMyGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetMyGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetMyGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetMyGroups(ctx, req.(*GetMyGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).InviteMember(ctx, req.(*InviteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_RespondInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).RespondInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_RespondInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).RespondInvitation(ctx, req.(*RespondInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_CancelInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).CancelInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_CancelInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).CancelInvitation(ctx, req.(*CancelInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetMyGroupInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyGroupInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetMyGroupInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetMyGroupInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetMyGroupInvitations(ctx, req.(*GetMyGroupInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GenerateGroupUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateGroupUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GenerateGroupUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GenerateGroupUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GenerateGroupUrl(ctx, req.(*GenerateGroupUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_JoinGroupByUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupByUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).JoinGroupByUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_JoinGroupByUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).JoinGroupByUrl(ctx, req.(*JoinGroupByUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_FindGroupByInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindGroupByInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).FindGroupByInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_FindGroupByInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).FindGroupByInviteCode(ctx, req.(*FindGroupByInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_GetGroupWithDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupWithDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).GetGroupWithDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_GetGroupWithDisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).GetGroupWithDisplayName(ctx, req.(*GetGroupWithDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VagueService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VagueServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VagueService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VagueServiceServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VagueService_ServiceDesc is the grpc.ServiceDesc for VagueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VagueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.VagueService",
	HandlerType: (*VagueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastEventRevision",
			Handler:    _VagueService_GetLastEventRevision_Handler,
		},
		{
			MethodName: "GetLastViewRevision",
			Handler:    _VagueService_GetLastViewRevision_Handler,
		},
		{
			MethodName: "RegisterPublicKey",
			Handler:    _VagueService_RegisterPublicKey_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _VagueService_GetPublicKey_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _VagueService_SendMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _VagueService_GetMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _VagueService_DeleteMessage_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _VagueService_RefreshToken_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _VagueService_EditMessage_Handler,
		},
		{
			MethodName: "GetOriginMessage",
			Handler:    _VagueService_GetOriginMessage_Handler,
		},
		{
			MethodName: "UploadMedia",
			Handler:    _VagueService_UploadMedia_Handler,
		},
		{
			MethodName: "BackupE2EEKey",
			Handler:    _VagueService_BackupE2EEKey_Handler,
		},
		{
			MethodName: "RestoreE2EEKey",
			Handler:    _VagueService_RestoreE2EEKey_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _VagueService_UpdateSettings_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _VagueService_GetSettings_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _VagueService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _VagueService_UpdateProfile_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _VagueService_SearchUsers_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _VagueService_AddFriend_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _VagueService_GetFriends_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _VagueService_GetContacts_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _VagueService_UpdateContact_Handler,
		},
		{
			MethodName: "GetBlockedUsers",
			Handler:    _VagueService_GetBlockedUsers_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _VagueService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _VagueService_GetGroup_Handler,
		},
		{
			MethodName: "GetMyGroups",
			Handler:    _VagueService_GetMyGroups_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _VagueService_UpdateGroup_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _VagueService_InviteMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _VagueService_RemoveMember_Handler,
		},
		{
			MethodName: "RespondInvitation",
			Handler:    _VagueService_RespondInvitation_Handler,
		},
		{
			MethodName: "CancelInvitation",
			Handler:    _VagueService_CancelInvitation_Handler,
		},
		{
			MethodName: "GetMyGroupInvitations",
			Handler:    _VagueService_GetMyGroupInvitations_Handler,
		},
		{
			MethodName: "GenerateGroupUrl",
			Handler:    _VagueService_GenerateGroupUrl_Handler,
		},
		{
			MethodName: "JoinGroupByUrl",
			Handler:    _VagueService_JoinGroupByUrl_Handler,
		},
		{
			MethodName: "FindGroupByInviteCode",
			Handler:    _VagueService_FindGroupByInviteCode_Handler,
		},
		{
			MethodName: "GetGroupWithDisplayName",
			Handler:    _VagueService_GetGroupWithDisplayName_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _VagueService_LeaveGroup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStreamMultipleEvent",
			Handler:       _VagueService_ChatStreamMultipleEvent_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bot.proto",
}
